export const FETCH_STOCK_DATA_REQUEST = 'FETCH_STOCK_DATA_REQUEST'
export const FETCH_STOCK_DATA_SUCCESS = 'FETCH_STOCK_DATA_SUCCESS'
export const FETCH_STOCK_DATA_FAILURE = 'FETCH_STOCK_DATA_FAILURE'
export const REQUEST_API_CALL_INFO = 'REQUEST_API_CALL_INFO'