export const ADD_TICKER = 'ADD_TICKER'
export const FETCH_COMP_INFO_REQUEST = 'FETCH_COMP_INFO_REQUEST'
export const FETCH_COMP_INFO_SUCCESS = 'FETCH_COMP_INFO_SUCCESS'
export const FETCH_COMP_INFO_FAILURE = 'FETCH_COMP_INFO_FAILURE'